# Generated by Django 5.2.17 on 2026-09-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecology",
            "0002_alter_simulationrun_options_simulationcleanuppreview_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="kind",
            field=models.CharField(
                choices=[
                    ("river", "河流"),
                    ("lake", "湖泊"),
                    ("park", "公园"),
                    ("plant", "植物点"),
                    ("waste", "分类投放点"),
                    ("trail", "绿色步道"),
                    ("campus", "校园地点"),
                    ("landmark", "地标与停留点"),
                ],
                max_length=20,
            ),
        ),
    ]
