# Generated by Django 5.2.17 on 2026-10-03 08:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyBudget",
            fields=[
                ("day", models.DateField(primary_key=True, serialize=False)),
                ("reserved_bytes", models.PositiveBigIntegerField(default=0)),
                ("requests", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="StagingState",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_id", models.UUIDField()),
                ("purpose", models.CharField(max_length=20)),
                ("total_size", models.PositiveIntegerField()),
                ("offset", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="open", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assets.asset",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("data", models.BinaryField()),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="cloudtransfer.upload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OwnerBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("reserved_bytes", models.PositiveBigIntegerField(default=0)),
                ("requests", models.PositiveIntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "day"), name="cloud_budget_owner_day"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="upload",
            constraint=models.UniqueConstraint(
                fields=("owner", "request_id"), name="cloud_upload_owner_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="chunk",
            constraint=models.UniqueConstraint(
                fields=("upload", "index"), name="cloud_upload_chunk_index"
            ),
        ),
    ]
