# Generated by Django 5.2.17 on 2026-09-23 16:03

import django.db.models.deletion
import narration.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knowledge", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Narration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                (
                    "audio",
                    models.FileField(
                        storage=narration.storage.PrivateNarrationStorage(),
                        upload_to="audio/",
                    ),
                ),
                ("mime_type", models.CharField(max_length=32)),
                ("byte_size", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("source_revision", models.CharField(max_length=64)),
                ("rights_note", models.CharField(max_length=500)),
                ("copyright_confirmed", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "待发布"),
                            ("published", "已发布"),
                            ("withdrawn", "已撤下"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="narrations",
                        to="knowledge.content",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_narrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="narrations",
                        to="knowledge.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "授权语音讲解",
                "verbose_name_plural": "授权语音讲解",
                "ordering": ["-created_at"],
                "permissions": [("publish_narration", "可审核发布授权语音讲解")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("content__isnull", False), ("route__isnull", True)
                            ),
                            models.Q(
                                ("content__isnull", True), ("route__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="narration_exactly_one_source",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "published")),
                        fields=("content",),
                        name="narration_one_published_content",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "published")),
                        fields=("route",),
                        name="narration_one_published_route",
                    ),
                ],
            },
        ),
    ]
