'use strict';
const test = require('node:test'); const assert = require('node:assert/strict'); const { EventEmitter } = require('node:events'); const zlib = require('node:zlib');
const { exchange, ProviderError, validMessages } = require('../../cloudfunctions/hyhqApi/lib/providers');
function fakeResponse(status, headers = {}, chunks = [], finish = true) {
  let calls = 0, destroyed = 0;
  const request = (options, callback) => { calls++; assert.equal(options.protocol, 'https:'); assert.equal(options.rejectUnauthorized, true); const req = new EventEmitter(); req.destroy = () => { destroyed++; }; req.end = () => queueMicrotask(() => { const res = new EventEmitter(); res.statusCode = status; res.headers = headers; res.destroy = () => { destroyed++; }; callback(res); for (const chunk of chunks) res.emit('data', Buffer.from(chunk)); if (finish) res.emit('end'); }); return req; };
  return { request, calls: () => calls, destroyed: () => destroyed };
}
test('HTTP redirect is not followed and error body is not exposed', async () => { const fake = fakeResponse(302, { location: 'https://attacker.invalid/secret' }, ['secret-api-key']); await assert.rejects(exchange({ hostname: 'api.deepseek.com' }, null, { request: fake.request }), (e) => e instanceof ProviderError && e.status === 302 && !e.message.includes('secret')); assert.equal(fake.calls(), 1); assert.equal(fake.destroyed(), 1); });
test('hard deadline terminates a server that never completes', async () => { const fake = fakeResponse(200, {}, ['{"open":'], false), start = Date.now(); await assert.rejects(exchange({ hostname: 'api.deepseek.com' }, null, { request: fake.request, timeoutMs: 20 }), (e) => e.code === 'timeout'); assert.ok(Date.now() - start < 1000); assert.equal(fake.calls(), 1); assert.ok(fake.destroyed() > 0); });
test('content length and streaming size both enforce upper bounds', async () => { for (const fake of [fakeResponse(200, { 'content-length': '999' }), fakeResponse(200, {}, [Buffer.alloc(40)])]) await assert.rejects(exchange({ hostname: 'unit.qweatherapi.com' }, null, { request: fake.request, maxBytes: 30 }), (e) => e.code === 'response_too_large'); });
test('gzip expansion and malformed UTF8 fail closed', async () => { const gzip = fakeResponse(200, { 'content-encoding': 'gzip' }, [zlib.gzipSync(Buffer.alloc(10000))]); await assert.rejects(exchange({ hostname: 'unit.qweatherapi.com' }, null, { request: gzip.request, maxBytes: 100, gzip: true }), (e) => e.code === 'invalid_response'); const invalid = fakeResponse(200, {}, [Buffer.from([123,34,120,34,58,34,255,34,125])]); await assert.rejects(exchange({ hostname: 'api.deepseek.com' }, null, { request: invalid.request }), (e) => e.code === 'invalid_response'); });
test('successful bounded JSON resolves once', async () => { const fake = fakeResponse(200, {}, ['{"ok":', 'true}']); assert.deepEqual(await exchange({ hostname: 'unit.qweatherapi.com' }, null, { request: fake.request }), { ok: true }); assert.equal(fake.calls(), 1); });
test('message validation disallows remote images and oversized context', () => { assert.throws(() => validMessages([{ role: 'user', content: [{ type: 'image_url', image_url: { url: 'https://attacker.invalid/picture' } }] }])); assert.throws(() => validMessages([{ role: 'user', content: 'x'.repeat(16385) }])); assert.throws(() => validMessages([{ role: 'user', content: [] }])); });
