'use strict';
const test = require('node:test'); const assert = require('node:assert/strict');
const { MemoryStore } = require('./memory-store');
const weather = require('../../cloudfunctions/hyhqApi/lib/weather');
const provider = require('../../cloudfunctions/hyhqApi/lib/providers');
const NOW = '2026-10-03T04:00:00.000Z';
function context(options = {}) { return { method: 'GET', path: 'weather-data/summary/', query: new URLSearchParams('location=tianjin'), body: {}, now: NOW, store: new MemoryStore(), config: { qweatherEnabled: true, qweatherBudgetConfirmed: true, qweatherApiKey: 'fake-test-only-key', qweatherApiHost: 'unit.qweatherapi.com', qweatherMonthlyLimit: 30 }, ...options }; }
function payload(kind) { return { data: kind === 'alerts' ? { items: [], zero_result: true } : { temperature: 22, condition: '晴' }, attributions: ['Official fixture attribution'], refer: { sources: ['QWeather'] }, observed_at: null }; }
function cached(kind, extra = {}) { return { id: `tianjin_${kind}`, kind, location: 'tianjin', payload: payload(kind), fetched_at: '2026-10-03T03:55:00.000Z', expires_at: '2026-10-03T04:15:00.000Z', ...extra }; }
test('fixed ten cities and three compatible campus locations keep forecast disabled', async () => {
  const ctx = context({ path: 'weather-data/locations/', query: new URLSearchParams() }), result = (await weather.handle(ctx)).data.data;
  assert.equal(result.items.length, 13); assert.equal(new Set(result.items.map(x => x.slug)).size, 13);
  assert.deepEqual(result.items.filter(x => x.kind === 'city').map(x => x.slug).sort(), ['beijing', 'chengdu', 'chongqing', 'guangzhou', 'hangzhou', 'nanjing', 'shanghai', 'shenzhen', 'tianjin', 'wuhan']);
  assert.deepEqual(result.items.filter(x => x.kind === 'campus').map(x => x.slug), ['tiangong', 'tianjin-normal', 'tianjin-technology']);
  assert.equal(result.forecast_enabled, false); assert.ok(result.items.every(x => x.coordinate_system === 'WGS84'));
  assert.match(result.items.find(x => x.slug === 'tiangong').scope_note, /不是校园内实测/);
  assert.match(result.items.find(x => x.slug === 'beijing').scope_note, /城市代表点/);
});
test('zero budget or missing confirmation never calls upstream', async () => { for (const config of [{ qweatherMonthlyLimit: 0 }, { qweatherBudgetConfirmed: false }, { qweatherApiHost: 'attacker.example' }, { qweatherEnabled: false }]) { const ctx = context(); Object.assign(ctx.config, config); const result = await weather.handle(ctx, { fetchWeather: () => assert.fail('network must remain disabled') }); assert.equal(result.data.data.weather.status, 'unavailable'); assert.equal(await ctx.store.count('weather_requests'), 0); } });
test('unknown location, duplicate query, and arbitrary query are rejected', async () => { for (const query of ['location=other', 'location=tianjin&location=beijing', 'location=tianjin&host=bad']) await assert.rejects(weather.handle(context({ query: new URLSearchParams(query) }))); });
test('weather components reserve three requests and reuse caches', async () => { const ctx = context(); let calls = 0; const adapters = { fetchWeather: async (_, kind) => { calls++; return payload(kind); } }; const result = (await weather.handle(ctx, adapters)).data.data; assert.equal(result.weather.status, 'fresh'); assert.equal(result.alerts.status, 'empty'); await weather.handle(ctx, adapters); assert.equal(calls, 3); assert.equal(await ctx.store.count('weather_requests'), 3); });
test('concurrent cache misses issue only one upstream call per component', async () => { const ctx = context(); let calls = 0; const fetcher = async (_, kind) => { calls++; await new Promise((r) => setTimeout(r, 10)); return payload(kind); }; const replies = await Promise.all(Array.from({ length: 10 }, () => weather.component(ctx, weather.LOCATIONS[0], 'weather', fetcher))); assert.equal(calls, 1); assert.equal(await ctx.store.count('weather_requests'), 1); assert.ok(replies.some((x) => x.reason === 'refreshing')); });
test('concurrent different locations cannot overrun project allocation', async () => { const ctx = context(); ctx.config.qweatherMonthlyLimit = 2; let calls = 0; await Promise.all(weather.LOCATIONS.map((location) => weather.component(ctx, location, 'weather', async (_, kind) => { calls++; return payload(kind); }))); assert.equal(calls, 2); assert.equal(await ctx.store.count('weather_requests'), 2); });
test('rolling 31 days remains binding after calendar month changes', async () => { const ctx = context(); ctx.config.qweatherMonthlyLimit = 3; await ctx.store.set('weather_gate', 'budget', { id: 'budget', days: { '2026-09-30': 3 }, recent: [] }); const reply = await weather.component(ctx, weather.LOCATIONS[0], 'weather', () => assert.fail()); assert.equal(reply.reason, 'budget_exhausted'); });
test('failures retain reservations and impose cooldown', async () => { const ctx = context(); const fetcher = async () => { throw new provider.ProviderError('timeout'); }; assert.equal((await weather.component(ctx, weather.LOCATIONS[0], 'weather', fetcher)).reason, 'timeout'); await weather.component(ctx, weather.LOCATIONS[0], 'weather', () => assert.fail()); assert.equal(await ctx.store.count('weather_requests'), 1); assert.equal((await ctx.store.get('weather_gate', 'budget')).days['2026-10-03'], 1); });
test('provider quota/auth failures block subsequent components without extra spend', async () => { const ctx = context(); let calls = 0; const result = await weather.handle(ctx, { fetchWeather: async () => { calls++; throw new provider.ProviderError('upstream_http', { status: 429 }); } }); assert.equal(calls, 1); assert.equal(result.data.data.air.reason, 'upstream_rate_limited'); });
test('minute burst limit caps upstream requests', async () => { const ctx = context(); await ctx.store.set('weather_gate', 'budget', { id: 'budget', days: {}, recent: Array(15).fill(Date.parse(NOW) - 1000) }); const out = await weather.component(ctx, weather.LOCATIONS[0], 'air', () => assert.fail()); assert.equal(out.reason, 'rate_limited'); });
test('cache context performs reads only and withholds expired facts', async () => { const ctx = context(); await ctx.store.set('weather_cache', 'tianjin_weather', cached('weather', { expires_at: '2026-10-03T03:59:00.000Z' })); const before = JSON.stringify([...ctx.store.data]); const out = await weather.readContext(ctx, 'tianjin'); assert.equal(out.components.weather.status, 'stale'); assert.equal(out.components.weather.data, null); assert.equal(out.cache_only, true); assert.equal(JSON.stringify([...ctx.store.data]), before); });
test('future and old observation times cannot become current weather', () => { for (const value of ['2026-10-04T00:00:00Z', '2026-10-02T00:00:00Z', 'invalid']) { const cache = cached('weather'); cache.payload.observed_at = value; assert.equal(weather.safeContextComponent(cache, Date.parse(NOW)).data, null); } });
test('context keeps full attribution or omits whole oversized component', async () => { const ctx = context(), cache = cached('weather'); cache.payload.attributions = ['x'.repeat(5000)]; await ctx.store.set('weather_cache', 'tianjin_weather', cache); const out = await weather.readContext(ctx, 'tianjin'); assert.equal(out.components.weather.reason, 'context_budget_exceeded'); assert.equal(out.components.weather.data, null); assert.ok(Buffer.byteLength(JSON.stringify(out)) <= 3500); });
test('unselected or unknown location never guesses current city', async () => { const ctx = context(); assert.equal((await weather.readContext(ctx, '')).reason, 'weather_location_required'); assert.equal((await weather.readContext(ctx, 'unknown')).reason, 'location_unavailable'); });
test('forecast and subscription endpoints stay explicitly closed', async () => { const ctx = context({ path: 'weather-data/beijing/forecast/', query: new URLSearchParams() }); assert.equal((await weather.handle(ctx)).data.data.enabled, false); ctx.path = 'weather-data/reminders/'; assert.equal((await weather.handle(ctx)).data.data.reason, 'native_subscription_not_implemented'); ctx.path = 'weather-data/reminders/intents/'; ctx.method = 'POST'; ctx.user = { id: 'user' }; await assert.rejects(weather.handle(ctx), (e) => e.code === 'SUBSCRIPTIONS_DISABLED'); });
test('all excluded weather products and forecast are absent from transport allowlist', async () => { for (const kind of ['cyclone', 'marine', 'solar', 'radiation', 'forecast', '../weather']) await assert.rejects(provider.fetchWeather(context().config, kind, weather.LOCATIONS[0], () => assert.fail()), (e) => e.code === 'unsupported_kind'); });
test('provider request uses fixed host/path and exact secret header without URL credentials', async () => { let request; const config = context().config; const result = await provider.fetchWeather(config, 'weather', weather.LOCATIONS[0], async (options, _, bounds) => { request = options; assert.equal(bounds.timeoutMs, 5000); return { metadata: { attributions: ['source'] }, temperature: { value: 21, unit: '°C' }, condition: { text: '晴' }, humidity: 0.6 }; }); assert.equal(request.hostname, 'unit.qweatherapi.com'); assert.equal(request.path, '/weather/v1/current/39.09/117.20?lang=zh'); assert.equal(request.headers['X-QW-Api-Key'], config.qweatherApiKey); assert.equal(result.data.humidity_percent, 60); });
test('foreign AQI retains its index, missing weather is not converted to zero', () => { const result = provider.normalizeWeather('air', { metadata: { attributions: [] }, indexes: [{ code: 'us-epa', name: 'US AQI', aqi: 5 }] }); assert.equal(result.data.index_code, 'us-epa'); assert.throws(() => provider.normalizeWeather('weather', { metadata: { attributions: [] }, temperature: { value: null }, condition: { text: '晴' } })); });
test('alerts only become empty on explicit valid zero flag', () => { assert.equal(provider.normalizeWeather('alerts', { metadata: { zeroResult: true } }).data.zero_result, true); assert.throws(() => provider.normalizeWeather('alerts', { metadata: { attributions: [] }, alerts: [] })); });
test('GPS coordinates and alternate endpoint requests cannot create weather records or bypass slug allowlist', async () => {
  for (const options of [{ query: new URLSearchParams('location=beijing&latitude=39.9088&longitude=116.3973') }, { query: new URLSearchParams('latitude=39.9088&longitude=116.3973') }, { body: { latitude: 39.9088, longitude: 116.3973 } }, { query: new URLSearchParams('location=39.9088,116.3973') }]) {
    const ctx = context(options); await assert.rejects(weather.handle(ctx, { fetchWeather: () => assert.fail('coordinate request cannot reach provider') }));
    assert.equal(ctx.store.data.size, 0);
  }
});
test('new cities use the existing three products and shared cache budget with no new provider paths', async () => {
  for (const slug of ['shanghai', 'guangzhou', 'shenzhen', 'hangzhou', 'chengdu', 'chongqing', 'wuhan', 'nanjing']) {
    const ctx = context({ query: new URLSearchParams('location=' + slug) }), calls = [];
    const adapters = { fetchWeather: async (_, kind, location) => { calls.push({ kind, slug: location.slug }); assert.deepEqual(location, weather.locationFor(slug)); return payload(kind); } };
    const out = (await weather.handle(ctx, adapters)).data.data;
    assert.equal(out.location.slug, slug); assert.deepEqual(calls.map(x => x.kind), ['weather', 'air', 'alerts']);
    await weather.handle(ctx, adapters); assert.equal(calls.length, 3);
    assert.equal((await ctx.store.get('weather_gate', 'budget')).days['2026-10-03'], 3);
    assert.ok((await ctx.store.list('weather_requests')).every(row => row.location === slug && !('latitude' in row) && !('longitude' in row)));
  }
});
