# Generated by Django 5.2.17 on 2026-09-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0002_remove_llmsession_llm_one_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmsession",
            name="weather_location",
            field=models.SlugField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="llmturn",
            name="citations",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
