# Generated by Django 5.2.17 on 2026-09-23 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ecology", "0003_place_landmark_kind"),
        ("knowledge", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "未通过"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "safety_status",
                    models.CharField(
                        choices=[
                            ("pass", "微信检测通过"),
                            ("review", "微信建议复审"),
                            ("risky", "微信检测未通过"),
                        ],
                        default="review",
                        max_length=12,
                    ),
                ),
                ("safety_trace_id", models.CharField(blank=True, max_length=128)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "moderation_note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="内部审核备注"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge.content",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecology.place",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户评论",
                "verbose_name_plural": "用户评论",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=False, verbose_name="管理员启用"),
                ),
                (
                    "personal_eligibility_confirmed",
                    models.BooleanField(
                        default=False,
                        verbose_name="已核实个人主体当前业务范围支持公开评论",
                    ),
                ),
                (
                    "eligibility_evidence",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="平台核实记录或工单依据（不填密钥）",
                    ),
                ),
                (
                    "eligibility_confirmed_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="资格核实日期"
                    ),
                ),
                (
                    "moderation_ready",
                    models.BooleanField(
                        default=False, verbose_name="人工审核流程及值守已就绪"
                    ),
                ),
                (
                    "safety_verified_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="微信文本安全接口最近成功核验",
                    ),
                ),
                (
                    "safety_credential_digest",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="负责审核的管理员",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论开放条件",
                "verbose_name_plural": "评论开放条件",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "广告或无关信息"),
                            ("abuse", "辱骂或不当内容"),
                            ("privacy", "泄露隐私"),
                            ("inaccurate", "内容存在错误"),
                            ("other", "其他问题"),
                        ],
                        max_length=16,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("resolved", "已处理"),
                            ("dismissed", "不予受理"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "moderation_note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="内部处理备注"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.comment",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge.content",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecology.place",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户举报",
                "verbose_name_plural": "用户举报",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionAttempt",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[("comment", "评论"), ("report", "举报")], max_length=10
                    ),
                ),
                ("request_id", models.UUIDField()),
                ("state", models.CharField(default="processing", max_length=12)),
                ("result_id", models.UUIDField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pk__isnull", True),
                    models.Q(
                        ("content__isnull", False),
                        ("route__isnull", True),
                        ("place__isnull", True),
                    ),
                    models.Q(
                        ("route__isnull", False),
                        ("content__isnull", True),
                        ("place__isnull", True),
                    ),
                    models.Q(
                        ("place__isnull", False),
                        ("content__isnull", True),
                        ("route__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="community_comment_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "approved"), _negated=True),
                    ("safety_status", "pass"),
                    _connector="OR",
                ),
                name="community_approved_safety_pass",
            ),
        ),
        migrations.AddConstraint(
            model_name="configuration",
            constraint=models.CheckConstraint(
                condition=models.Q(("id", 1)), name="community_single_configuration"
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pk__isnull", True),
                    models.Q(
                        ("content__isnull", False),
                        ("route__isnull", True),
                        ("place__isnull", True),
                        ("comment__isnull", True),
                    ),
                    models.Q(
                        ("route__isnull", False),
                        ("content__isnull", True),
                        ("place__isnull", True),
                        ("comment__isnull", True),
                    ),
                    models.Q(
                        ("place__isnull", False),
                        ("content__isnull", True),
                        ("route__isnull", True),
                        ("comment__isnull", True),
                    ),
                    models.Q(
                        ("comment__isnull", False),
                        ("content__isnull", True),
                        ("route__isnull", True),
                        ("place__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="community_report_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                condition=models.Q(("content__isnull", False)),
                fields=("owner", "content"),
                name="community_report_unique_content",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                condition=models.Q(("route__isnull", False)),
                fields=("owner", "route"),
                name="community_report_unique_route",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                condition=models.Q(("place__isnull", False)),
                fields=("owner", "place"),
                name="community_report_unique_place",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                condition=models.Q(("comment__isnull", False)),
                fields=("owner", "comment"),
                name="community_report_unique_comment",
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionattempt",
            constraint=models.UniqueConstraint(
                fields=("owner", "kind", "request_id"),
                name="community_idempotent_attempt",
            ),
        ),
    ]
