# Generated by Django 5.2.17 on 2026-09-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyDay",
            fields=[
                ("day", models.DateField(primary_key=True, serialize=False)),
                ("calls", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
