# Generated by Django 5.2.17 on 2026-09-23 15:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weatherdata", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="weathercache",
            name="kind",
            field=models.CharField(
                choices=[
                    ("weather", "当前天气"),
                    ("air", "当前空气质量"),
                    ("alerts", "当前天气预警"),
                    ("forecast", "每日天气预报"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="weatherrequest",
            name="kind",
            field=models.CharField(
                choices=[
                    ("weather", "当前天气"),
                    ("air", "当前空气质量"),
                    ("alerts", "当前天气预警"),
                    ("forecast", "每日天气预报"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="WeatherReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("point", models.CharField(max_length=30)),
                ("template_id", models.CharField(max_length=128)),
                ("config_fingerprint", models.CharField(max_length=64)),
                ("target_date", models.DateField()),
                ("scheduled_for", models.DateTimeField(db_index=True)),
                ("expires_at", models.DateTimeField()),
                ("consent_expires_at", models.DateTimeField()),
                ("consented_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("prepared", "待主动授权"),
                            ("pending", "已安排"),
                            ("sending", "发送中"),
                            ("retry", "等待重试"),
                            ("sent", "已发送"),
                            ("cancelled", "已取消"),
                            ("expired", "已过期"),
                            ("failed", "发送失败"),
                            ("unknown", "发送结果待核实"),
                        ],
                        db_index=True,
                        default="prepared",
                        max_length=12,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_code", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="weatherdata.weatherlocation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "一次天气提醒",
                "verbose_name_plural": "一次天气提醒",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeatherReminderAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("outcome", models.CharField(default="started", max_length=40)),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_attempts",
                        to="weatherdata.weatherreminder",
                    ),
                ),
            ],
            options={
                "verbose_name": "天气提醒发送记录",
                "verbose_name_plural": "天气提醒发送记录",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="weatherreminder",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("state__in", ["prepared", "pending", "sending", "retry"])
                ),
                fields=("user", "target_date"),
                name="weather_one_active_reminder_per_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="weatherreminderattempt",
            constraint=models.UniqueConstraint(
                fields=("reminder", "number"), name="weather_unique_delivery_attempt"
            ),
        ),
    ]
